from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from typing import List
from app.schemas.patient import Patient, PatientCreate
from app.database import get_db, PatientDB, LabResultDB
from app import store
import datetime

router = APIRouter()

def _next_available_id(db: Session) -> str:
    all_patients = db.query(PatientDB).all()
    nums = set()
    for p in all_patients:
        pid = str(p.id)
        if pid.startswith("P") and pid[1:].isdigit():
            nums.add(int(pid[1:]))
    n = 1
    while n in nums:
        n += 1
    return f"P{str(n).zfill(3)}"

# ── SPECIFIC routes first ─────────────────────────────────────

@router.get("/next-id")
def get_next_patient_id(db: Session = Depends(get_db)):
    return {"next_id": _next_available_id(db)}

@router.get("/", response_model=List[Patient])
def list_patients(search: str = "", db: Session = Depends(get_db)):
    q = db.query(PatientDB)
    if search:
        q = q.filter(
            PatientDB.name.ilike(f"%{search}%") |
            PatientDB.id.ilike(f"%{search}%")
        )
    return q.all()

@router.post("/", response_model=Patient)
def create_patient(data: PatientCreate, db: Session = Depends(get_db)):
    if data.id:
        if db.query(PatientDB).filter(PatientDB.id == data.id).first():
            raise HTTPException(status_code=400, detail="Patient ID already exists")
        patient_id = data.id
    else:
        patient_id = _next_available_id(db)
    p = PatientDB(
        id=patient_id, name=data.name, age=data.age, gender=data.gender,
        risk="Unknown", dob=data.dob, contact=data.contact, address=data.address,
    )
    db.add(p)
    db.commit()
    db.refresh(p)
    store.add_audit_log("CREATE_PATIENT", "clinician", f"Created patient {patient_id} — {data.name}")
    return p

# ── PARAMETERIZED routes after ────────────────────────────────

@router.get("/{patient_id}/report", response_class=HTMLResponse)
def export_patient_report(patient_id: str, db: Session = Depends(get_db)):
    patient = db.query(PatientDB).filter(PatientDB.id == patient_id).first()
    if not patient:
        raise HTTPException(status_code=404, detail="Patient not found")
    results = db.query(LabResultDB).filter(LabResultDB.patient_id == patient_id).all()
    name    = str(patient.name)
    pid     = str(patient.id)
    age     = str(patient.age)
    gender  = str(patient.gender)
    risk    = str(patient.risk)
    contact = str(patient.contact or "—")
    rows = "".join([
        f"<tr><td>{r.test_name}</td><td>{r.result_value} {r.unit}</td><td>{r.reference_range}</td><td>{r.date}</td></tr>"
        for r in results
    ]) or "<tr><td colspan='4'>No lab results found</td></tr>"
    html = f"""<!DOCTYPE html><html><head><title>Report — {name}</title>
    <style>
      body{{font-family:Inter,sans-serif;padding:40px;color:#1e293b}}
      h1{{color:#0891b2}}h2{{color:#475569;margin-top:32px}}
      table{{width:100%;border-collapse:collapse;margin-top:12px}}
      th{{background:#f1f5f9;text-align:left;padding:8px 12px;font-size:13px}}
      td{{padding:8px 12px;border-bottom:1px solid #e2e8f0;font-size:13px}}
      .meta{{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}}
      .meta-item{{background:#f8fafc;padding:10px 14px;border-radius:8px}}
      .label{{font-size:11px;color:#94a3b8}}.value{{font-size:14px;font-weight:600}}
      .footer{{margin-top:40px;font-size:12px;color:#94a3b8}}
    </style></head><body>
    <h1>LabTrend-CDSS</h1>
    <p style="color:#64748b">Patient Summary Report — Generated {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
    <h2>Patient Details</h2>
    <div class="meta">
      <div class="meta-item"><div class="label">Patient ID</div><div class="value">{pid}</div></div>
      <div class="meta-item"><div class="label">Full Name</div><div class="value">{name}</div></div>
      <div class="meta-item"><div class="label">Age</div><div class="value">{age}</div></div>
      <div class="meta-item"><div class="label">Gender</div><div class="value">{gender}</div></div>
      <div class="meta-item"><div class="label">Risk Level</div><div class="value">{risk}</div></div>
      <div class="meta-item"><div class="label">Contact</div><div class="value">{contact}</div></div>
    </div>
    <h2>Lab Results</h2>
    <table><thead><tr><th>Test</th><th>Result</th><th>Reference Range</th><th>Date</th></tr></thead>
    <tbody>{rows}</tbody></table>
    <div class="footer">This report is generated by LabTrend-CDSS for clinical reference only.</div>
    </body></html>"""
    return HTMLResponse(content=html)

@router.get("/{patient_id}", response_model=Patient)
def get_patient(patient_id: str, db: Session = Depends(get_db)):
    p = db.query(PatientDB).filter(PatientDB.id == patient_id).first()
    if not p:
        raise HTTPException(status_code=404, detail="Patient not found")
    return p

@router.put("/{patient_id}", response_model=Patient)
def update_patient(patient_id: str, data: PatientCreate, db: Session = Depends(get_db)):
    p = db.query(PatientDB).filter(PatientDB.id == patient_id).first()
    if not p:
        raise HTTPException(status_code=404, detail="Patient not found")
    for key, value in data.dict().items():
        if value is not None:
            setattr(p, key, value)
    db.commit()
    db.refresh(p)
    store.add_audit_log("EDIT_PATIENT", "clinician", f"Updated patient {patient_id} — {str(p.name)}")
    return p